name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@d7a9d717d17a1093fdcc9f6f8d644ab0847283e3
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
